---
  - name: restart zabbix-server
    service:
      name: zabbix-server
      state: restarted
      enabled: yes

  - name: Check if zabbix-agent started
    service:
      name: zabbix-agent
      state: started
      enabled: yes

  - name: restart zabbix-agent
    service:
      name: zabbix-agent
      state: restarted
      enabled: yes

  - name: restart mysql
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: restart php70-php-fpm
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes