---

  - name: Install nginx repository (CentOS/Amazon Linux)
    yum_repository:
      name: nginx-repo
      description: nginx repository
      baseurl: http://nginx.org/packages/centos/7/$basearch/
      gpgcheck: no
      enabled: yes
    tags: nginx
    when: ansible_architecture == "x86_64"

  - name: Enable nginx ({{ansible_distribution}})
    shell: amazon-linux-extras enable nginx1
    when: ansible_architecture == "aarch64" 

  - name: yum-clean-all
    command: yum clean all
    args:
      warn: no
    tags: nginx
    ignore_errors: yes

  - name: Install nginx packages
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - "{{ packages[ansible_os_family] }}"
    tags: nginx

  - name: Configure nginx
    template:
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx
    tags: nginx

  - name: Removing default config files
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
      - /etc/nginx/conf.d/*.conf
    notify:
      - restart nginx
    tags: nginx

  - name: Install default website
    template:
      src: etc/nginx/conf.d/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
    notify:
      - restart nginx
    tags: nginx
